use anyhow::Result;
use colored::*;
use std::fs;
use std::path::PathBuf;

pub fn run(output: PathBuf) -> Result<()> {
    if output.exists() {
        eprintln!(
            "{} Configuration file already exists: {}",
            "⚠".yellow().bold(),
            output.display().to_string().yellow()
        );
        eprintln!("Delete it first or use a different path.\n");
        anyhow::bail!("Configuration file already exists");
    }

    let config_template = r#"# ELOIZER Configuration File
# Generated by: eloizer init

[analysis]
# Path to analyze (can be overridden via CLI)
path = "src/"

# Generate AST JSON files
generate_ast = false

[output]
# Output report file path
report_file = "security-report.md"

[rules]
# Severities to ignore (options: high, medium, low, informational)
ignore_severities = []

# Specific rule IDs to ignore
ignore_rules = []

# Rule types to include (options: solana, anchor, general)
include_rule_types = ["solana", "anchor", "general"]

[display]
# Enable verbose output
verbose = false

# Quiet mode (errors only)
quiet = false

# Disable colored output
no_color = false
"#;

    fs::write(&output, config_template)?;

    println!(
        "\n{} Configuration file created: {}\n",
        "✓".green().bold(),
        output.display().to_string().bright_green()
    );

    println!("Edit the file to customize your analysis settings.");
    println!(
        "Run analysis with: {}\n",
        format!("eloizer config --config {}", output.display())
            .cyan()
            .bold()
    );

    Ok(())
}
